---
title: "Armed Conflict Location Event"
author: "Akira Sasaki"
date: "11/24/2017"
output: pdf_document
---

rm(list = ls())

```{r setup, include=FALSE, echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, error = TRUE, fig.pos = 'H', tidy.opts=list(width.cutoff=65), tidy=TRUE, fig.path='figs/', cache.path='cache/graphics-', 
           fig.pos ='H', fig.align='center', fig.width = 5, fig.height = 4, fig.show = 'hold',
           cache = TRUE, par = TRUE)
```

```{r library, include=FALSE, echo=FALSE}
library(shiny)
install.packages("shinydashboard")
library(shinydashboard)
library(scales)
library(foreign) #read foreign file objects
install.packages("dplyr", repos = "https://cran.rstudio.com/")
library(dplyr) #manipulate data
install.packages("ggplot2", repos = "https://cran.rstudio.com/")
library(ggplot2) #plot results
install.packages("psych", repos = "https://cran.rstudio.com/")
library(psych) #create summary statistics
library(plyr) #tools for splitting, qpplying and combining data
library(data.table)
require(haven)
library(lubridate)
install.packages("repmis", repos = "https://cran.rstudio.com/")
library(repmis)
library(data.table)
library(magrittr)
install.packages("stargazer")
library(stargazer)
install.packages("broom", repos = "https://cran.rstudio.com/")
library(broom)
install.packages("arm")
library(arm)
library(readr)
library(readxl)
library(tidyverse)
library(tidyr) 
library(stringr)
library(httr) 
install.packages("twitteR", repos = "https://cran.rstudio.com/")
library(twitteR)
library(rvest) 
install.packages("streamR", repos = "https://cran.rstudio.com/")
library(streamR)
install.packages("RCurl", repos = "https://cran.rstudio.com/")
library(RCurl)
install.packages("ROAuth", repos = "https://cran.rstudio.com/")
library(ROAuth)
install.packages("stringi", repos = "https://cran.rstudio.com/")
library(stringi)
install.packages("plm", repos = "https://cran.rstudio.com/")
library(plm)
install.packages("countrycode")
library(countrycode)

install.packages("foreign")
library(foreign)
install.packages("sandwich")
library(sandwich)
install.packages("lmtest")
library(lmtest)

install.packages("lfe")
library(lfe)
```

```{r data, include=FALSE, echo=FALSE}

ACLED <- read_csv("~/Armed-Conflict-Location-Event-Data/ACLED-Version-7-All-Africa-1997-2016_csv_dyadic-file.csv")
ACLED <- subset(ACLED, select = c("YEAR","EVENT_TYPE", "COUNTRY"))
names(ACLED)[names(ACLED) == 'COUNTRY'] <- "country"
names(ACLED)[names(ACLED) == 'YEAR'] <- 'year'
ACLED <- ACLED %>% dplyr::group_by(year, country, EVENT_TYPE) %>% dplyr::summarize(count = n())
ACLED <- apply(ACLED,2,toupper)

cat_social_conflict <- c("RIOTS/PROTESTS", "VIOLENCE AGAINST CIVILIANS")

ACLED <- ACLED %>% 
  as.data.frame()
ACLED2 <- ACLED %>% 
  dplyr::mutate(dep1 = ifelse(EVENT_TYPE %in% cat_social_conflict, "CIVILIAN INVOLVED CONFLICT", "ARMED GROUP CONFLICT" ))

ACLED2$count <- as.numeric(ACLED2$count)
ACLED2 <- ACLED2 %>% 
  ungroup() %>%
  dplyr::group_by(country, year, dep1) %>%
  dplyr::summarise(dep2 = sum(count)) %>%
  spread(dep1, dep2)
ACLED2$iso3c <- countrycode(ACLED2$country, 'country.name','iso3c', warn = T)

GDP <- read_excel("~/Armed-Conflict-Location-Event-Data/Statistical model/GDP per capita/GDP.xlsx")
GDP <- apply(GDP,2,toupper)
GDP <- as.data.frame(GDP)
GDP$Country <- recode(GDP$Country,"CONGO"="Republic of Congo")
GDP$Country <- recode(GDP$Country,"CONGO (DEMOCRATIC REPUBLIC OF THE)"="Democratic Republic of Congo")
GDP$Country <- recode(GDP$Country,"CÔTE D'IVOIRE"="Ivory Coast")
GDP$Country <- recode(GDP$Country,"TANZANIA (UNITED REPUBLIC OF)"="Tanzania")
GDP <- as.data.frame(GDP)
names(GDP)[names(GDP)== "Country"] <- "country"
names(GDP)[names(GDP)== "score"] <- "GDP"
GDP <- GDP %>% gather(key = year, value = GDP, -country)
GDP$iso3c <- countrycode(GDP$country, 'country.name','iso3c', warn = T)
  
DATA <- merge(ACLED2, GDP, by=c("year","iso3c"))

<<<<<<< HEAD
DATA$iso3c <- countrycode(DATA$country, 'country.name', 
                        'iso3c', warn = T)

#Dependent variables natural log 
DATA$military.conflict <- as.numeric(as.character(DATA$military.conflict))
DATA$lnmilitary <- log1p(DATA$military.conflict)
DATA$social.conflict <- as.numeric(as.character(DATA$social.conflict))
DATA$lnsocial <- log1p(DATA$social.conflict)

=======
#Dependent variables natural log 
DATA$`ARMED GROUP CONFLICT` <- DATA$`ARMED GROUP CONFLICT` %>% as.numeric()
DATA$`CIVILIAN INVOLVED CONFLICT`<- DATA$`CIVILIAN INVOLVED CONFLICT` %>% as.numeric()
DATA$lnmilitary <- log(DATA$`ARMED GROUP CONFLICT`)
DATA$lnsocial <- log(DATA$`CIVILIAN INVOLVED CONFLICT`)
>>>>>>> 198a35e906bde23d96d7c636e462d8836e3beaca
```

```{r facebook data, include=FALSE, echo=FALSE}
#2010 Country names
url <- "https://web.archive.org/web/20101008034936/http://internetworldstats.com/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2010 <- html_nodes(url_parsed, css = css) %>% html_text

#2010info
url <- "https://web.archive.org/web/20101008034936/http://internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font"
url_parsed <- read_html(url)
country_info_2010 <- html_nodes(url_parsed, css = css) %>% html_text

#2011Country names
url <- "https://web.archive.org/web/20111002190951/http://www.internetworldstats.com:80/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2011 <- html_nodes(url_parsed, css = css) %>% html_text

#2011info
url <- "https://web.archive.org/web/20111002190951/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font"
url_parsed <- read_html(url)
country_info_2011 <- html_nodes(url_parsed, css = css) %>% html_text

#2012Country names
url <- "https://web.archive.org/web/20121014111737/http://www.internetworldstats.com:80/africa.htm"
css <- "img+ font b"
url_parsed <- read_html(url)
country_name_2012 <- html_nodes(url_parsed, css = css) %>% html_text

#2012info
url <- "https://web.archive.org/web/20121014111737/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2012 <- html_nodes(url_parsed, css = css) %>% html_text

#2013Country names
url <- "https://web.archive.org/web/20131015014009/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2013 <- html_nodes(url_parsed, css = css) %>% html_text

#2013info
url <- "https://web.archive.org/web/20131015014009/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2013 <- html_nodes(url_parsed, css = css) %>% html_text

#2014Country names
url <- "https://web.archive.org/web/20141013134528/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2014 <- html_nodes(url_parsed, css = css) %>% html_text

#2014info
url <- "https://web.archive.org/web/20141013134528/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2014 <- html_nodes(url_parsed, css = css) %>% html_text

#2015Country names
url <- "https://web.archive.org/web/20151020040350/http://www.internetworldstats.com:80/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2015 <- html_nodes(url_parsed, css = css) %>% html_text

#2015info
url <- "https://web.archive.org/web/20151020040350/http://www.internetworldstats.com:80/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2015 <- html_nodes(url_parsed, css = css) %>% html_text

#2016Country names
url <- "https://web.archive.org/web/20161001223626/http://www.internetworldstats.com/africa.htm"
css <- "font~ img+ font b"
url_parsed <- read_html(url)
country_name_2016 <- html_nodes(url_parsed, css = css) %>% html_text

#2016info
url <- "https://web.archive.org/web/20161001223626/http://www.internetworldstats.com/africa.htm"
css <- "tr:nth-child(9) font" 
url_parsed <- read_html(url)
country_info_2016 <- html_nodes(url_parsed, css = css) %>% html_text

n2010 <- data.frame(country_name_2010)  
i2010 <- data.frame(country_info_2010)
m2010 <- rbind(country_name_2010, country_info_2010)
m2010 <- data.frame(m2010)
m2010 <- t(m2010)
colnames(m2010) <- c("country", "data")
m2010 <- data.frame(m2010)
m2010$year="2010"

n2011 <- data.frame(country_name_2011)  
i2011 <- data.frame(country_info_2011)
m2011 <- rbind(country_name_2011, country_info_2011)
m2011 <- data.frame(m2011)
m2011 <- t(m2011)
colnames(m2011) <- c("country", "data")
m2011 <- data.frame(m2011)
m2011$year="2011"

n2012 <- data.frame(country_name_2012)  
i2012 <- data.frame(country_info_2012)
m2012 <- rbind(country_name_2012, country_info_2012)
m2012 <- data.frame(m2012)
m2012 <- t(m2012)
colnames(m2012) <- c("country", "data")
m2012 <- data.frame(m2012)
m2012$year="2012"

n2013 <- data.frame(country_name_2013)  
i2013 <- data.frame(country_info_2013)
m2013 <- rbind(country_name_2013, country_info_2013)
m2013 <- data.frame(m2013)
m2013 <- t(m2013)
colnames(m2013) <- c("country", "data")
m2013 <- data.frame(m2013)
m2013$year="2013"

n2014 <- data.frame(country_name_2014)  
i2014 <- data.frame(country_info_2014)
m2014 <- rbind(country_name_2014, country_info_2014)
m2014 <- data.frame(m2014)
m2014 <- t(m2014)
colnames(m2014) <- c("country", "data")
m2014 <- data.frame(m2014)
m2014$year="2014"

n2015 <- data.frame(country_name_2015)  
i2015 <- data.frame(country_info_2015)
m2015 <- rbind(country_name_2015, country_info_2015)
m2015 <- data.frame(m2015)
m2015 <- t(m2015)
colnames(m2015) <- c("country", "data")
m2015 <- data.frame(m2015)
m2015$year="2015"

n2016 <- data.frame(country_name_2016)  
i2016 <- data.frame(country_info_2016)
m2016 <- rbind(country_name_2016, country_info_2016)
m2016 <- data.frame(m2016)
m2016 <- t(m2016)
colnames(m2016) <- c("country", "data")
m2016 <- data.frame(m2016)
m2016$year="2016"

facebook <- rbind(m2010, m2011, m2012, m2013, m2014, m2015, m2016) 
facebook$data <- str_replace_all(facebook$data, ",", "")
facebook$subscription <- stri_extract_first_regex(facebook$data, "[0-9]+")
<<<<<<< HEAD
facebook$penetration <- str_extract(facebook$data, "((\\dd\\.\\d+)\\%)")
=======
facebook$penetration <- str_extract(facebook$data, "((\\d+\\.*\\d*)\\%)")
>>>>>>> 198a35e906bde23d96d7c636e462d8836e3beaca
facebook$penetration <- str_replace_all(facebook$penetration, "%", "")
facebook$data <- NULL
facebook$country <- gsub("EQUATORIAL\nGUINEA","EQUATORIAL GUINEA", facebook$country) 
facebook$country <-gsub("CENTRAL AFRICAN\n REPUBLIC","CENTRAL AFRICAN REPUBLIC", facebook$country) 
facebook <- data.frame(lapply(facebook, as.character), stringsAsFactors=FALSE)
facebook$iso3c <- countrycode(facebook$country, 'country.name', 
                             'iso3c', warn = T)
facebook<-data.frame(facebook)

DATA <- merge(DATA, facebook, by=c("year","iso3c"))
<<<<<<< HEAD
#subscription
DATA$subscription <- as.numeric(as.character(DATA$subscription))
DATA$lnsubscription <- log1p(DATA$subscription)
=======
DATA <- subset(DATA, select = -c(country.y, country))

#log subscription
DATA$subscription <- as.numeric(as.character(DATA$subscription))
DATA$lnsubscription <- log1p(DATA$subscription)

names(DATA)[names(DATA)== "country.x"] <- "country"
>>>>>>> 198a35e906bde23d96d7c636e462d8836e3beaca
```

```{r interactive plot, include=FALSE, echo=FALSE}
ui <- fluidPage(
  titlePanel("Armed Conflict Location Event"), # App title
  
  sidebarLayout(
    sidebarPanel( # Sidebar panel for inputs
      selectInput(inputId = "EVENT_TYPE", 
                  label = "Event type",
                  choices = unique(DATA$EVENT_TYPE),multiple=TRUE
      )),
    sidebarPanel( # Sidebar panel for inputs
      selectInput(inputId = "country", 
                  label = "Country",
                  choices = unique(DATA$country),multiple=TRUE
      )),
    mainPanel(
      tabsetPanel(
        tabPanel("Armed Conflict Location Event", plotOutput("lineChart"))
        # Output: Line Chart
      )
    )
  ))


server <- function(input, output) {
  
  # make line charts of events
  output$lineChart <- renderPlot({
    g<-ggplot(data=event(),aes(x=year, y=count))
    g<-g+geom_line() + 
      geom_point() +
      scale_x_discrete(limits = year) + 
      scale_y_continuous(labels=percent) +
      ggtitle( paste("Armed Conflicts")) +
      xlab("Year") + ylab("The number of reported cases")
    g
    
  })
  
}

shinyApp(ui = ui, server = server)


##for in case lists
c("STRATEGIC DEVELOPMENT","BATTLE-NO CHANGE OF TERRITORY","VIOLENCE AGAINST CIVILIANS","RIOTS/PROTESTS","BATTLE-GOVERNMENT REGAINS TERRITORY","REMOTE VIOLENCE","VIOLENCE AGAINST CIVILIANS","BATTLE-NON-STATE ACTOR OVERTAKES TERRITORY","NON-VIOLENT TRANSFER OF TERRITORY")

c("ALGERIA","ANGOLA","BENIN","BOTSWANA","BURKINA FASO","BURUNDI","CENTRAL AFRICAN REPUBLIC","CHAD","DJIBOUTI", "EGYPT", "EQUATORIAL GUINEA", "ERITREA", "ETHIOPIA", "GABON", "GAMBIA", "GHANA", "GUINEA", "GUINEA-BISSAU", "KENYA", "LESOTHO", "LIBERIA", "LIBYA", "MADAGASCAR", "MALAWI", "MALI", "MAURITANIA", "MOROCCO", "MOZAMBIQUE", "NAMIBIA", "NIGER", "NIGERIA", "RWANDA", "SENEGAL", "SIERRA LEONE", "SOUTH AFRICA", "SOUTH SUDAN", "SUDAN", "SWAZILAND", "TOGO", "TUNISIA", "UGANDA", "ZAMBIA", "ZIMBABWE")
```

```{r fixed effect regression, include=FALSE, echo=FALSE}

install.packages("ggExtra")
install.packages("ggplot2")
library(ggplot2)
library(ggExtra)

#social 2010
DATA[is.na(DATA)] <- 0
DATA2010 <-DATA
DATA2010 <- DATA2010[ which(DATA2010$year==2010), ]
DATA2010[] <- lapply(DATA2010, function(x) as.numeric(as.character(x)))
DATA2010$lnscore <- log1p(DATA2010$score)

civsoc10 <- DATA2010[DATA2010$lnsocial & DATA2010$lnsubscription , ]
g <- ggplot(DATA2010, aes(lnsubscription, lnsocial)) + 
  geom_count() + 
  geom_smooth(method="lm", se=F)+ 
  labs(subtitle="Facebook users Vs civil society conflict events", 
       y="Civil soc conflict", 
       x="Facebook", 
       title="Scatterplot", 
       caption = "Source: ACLED, UNDP")
g <-ggMarginal(g, type = "histogram", fill="transparent")

g

gg <- ggplot(DATA2010, aes(x=lnsubscription, y=lnsocial)) + 
  geom_point(aes(size=lnscore)) + 
  geom_smooth(method="loess", se=F) + 
  labs(subtitle="Facebook users Vs civil society conflict events", 
       y="Civil soc conflict", 
       x="Facebook", 
       title="Scatterplot", 
       caption = "Source: ACLED, UNDP")
plot(gg)

gg

reg10soc = lm(social.conflict ~ subscription + score, data= DATA2010)
coeftest(reg10soc, vcov = vcovHC(reg10soc, "HC1"))





####################################################

DATA1 <- DATA1[!(DATA1$iso3c %in% c("SSD", "MDG", "MLI", "MAR", "LSO")),]

table(DATA1$iso3c, DATA1$year)



fixed <- plm(lnsocial ~ lnsubscription, data=DATA1, index=c("iso3c", "year"), model="within")

summary(fixed)
#see https://www.princeton.edu/~otorres/Panel101R.pdf
<<<<<<< HEAD
#
=======

ACLED$count <- as.numeric(ACLED$count)
    g<-ggplot(data=ACLED,aes(x=year, y=count, group=country))
    g<-g+geom_line() + 
      geom_point() +
      ggtitle(paste("Armed Conflicts")) +
      xlab("Year") + ylab("The number of reported cases")
    g
    
    max(ACLED$count, na.rm = TRUE)
>>>>>>> 198a35e906bde23d96d7c636e462d8836e3beaca
```

